export const PPSData = [
  {
    id: "bukar_hassan",
    next: "sani_mamman",
    name: "Dr. Bukar Hassan",
    post: "Chairman / Chief Executive Officer",
    desc: "In addition, he has obtained a number of professional certificates from various International Academic and Research Institutions and these include; Certificate in the use of Meteosat and NOAA AVHRR and GIS for Rainfall and Vegetation Monitoring and Evaluation from Silsoe College, University of Bedford, UK; Certificate in Tropical Soil Management from University of Dresden, Germany; Certificate in Combating Desertification from Centre for Research in Desertification Control, Valencia, Spain.",
    summary:
      "Dr. Bukar Hassan with over 30 years experience in the Environmental Field is the Chairman and Chief Executive Officer of GPC. He holds a Bsc Degree in Botany from University of Maiduguri; Msc in Crop Production from University of Bath, UK and PhD in Arid Zone Ecology from University of Wales, UK.",
    further_desc:
      "Dr. Hassan started his career as lecturer and researcher at the University of Maiduguri before joining the Federal Civil service as an Environmental Scientist and served in various positions including,National Focal Point for the United Nations Convention to Combat Desertification (UNCCD), National Project Coordinator for Global Environment Facility (GEF) Assisted Integrated Ecosystem Management Project in the Transboundary Areas between Nigeria and Niger, Head (Programme Implementation Unit of the Great Green Wall Programme), Director (Drought and Desertification), Chairperson and Africa Representative (Committee for the Review of the Implementation of the Convention (CRIC) of the United Nations Convention to Combat Desertification), Permanent Secretary (Federal Ministry of Environment and Federal Ministry of Agriculture and Rural Development) and Director General/Chief Executive Officer (National Agency for the Great Green Wall among others. <br /> <br /> Dr. Hassan, a Fellow of Forestry Association of Nigeria (FAN) and recipient of Presidential Distinguished Public Civil Service Career Award has visited many countries on all the continents in the course of his studies and duties. He participated and represented Nigeria in many International Conferences and Meetings including UNEP Governing Council Meetings, Inter-Governmental Negotiating Committee for the Elaboration of International Convention to Combat Desertification; Regional Conference on the Implementation of the UN Convention to Combat Desertification in West Africa; Conferences of Parties to the UN Convention to Combat Desertification; Several Regional and Sub- Regional Meetings/Conferences/Seminars on Combating Drought and Desertification and Integrated Ecosystem Management Project in the Transboundary Areas between Nigeria and Niger; Several Meetings/Conferences, including Regular Technical and Ministerial Meetings on Great Green Wall.",
    img: "/images/bukar-hassan.png",
  },
  {
    id: "sani_mamman",
    next: "jauro_jibrin",
    name: "Sani Mamman Katsina",
    post: "Executive Director - Project Development",
    desc: "Mr. Katsina, a DAAD Fellow holds a Bsc degree in Geography from Bayero University Kano; Msc in Soil Science (Pedology and Soil Survey) from University of Reading, UK; Post Graduate Certificate in Biogeography and Regional Assessment (Environmental Statistics and Data Management) from University of Saarland, Germany; Certificate in Eco-Restoration and Biodiversity Protection from Gansu Desert Control Research Institute, China, Certificate in Combating Desertification Technology from Institute of Ecology and Geography, China and Certificate in World Soils Assessment from ISRIC, Wageningen, the Netherlands. Other professional programmes and training attended and certificates obtained include, Environmental Management Policy (USA); Scientific Instrumentation (Surrey UK); WHO Air Quality Monitoring (Nigeria); Farmers’ Managed Natural Regeneration (Niger Republic); Strategic Planning and Use of Geometric Tools for GGW Implementation (Sudan); Remote Sensing and GIS Training (Tunisia); Combating Desertification Technology (Turkey); and Combating Desertification and Sand and Dust Storm Management (Iran).",
    summary:
      "Sani Mamman Katsina is a fanatical environmentalist with over 30 years experience. His key focus is dryland management, ecorestoration, soil survey and Landuse planning, environmental statistics, environmental monitoring and coordination of environmental projects.",
    further_desc:
      "Before joining GSC, Mr. Katsina served on various positions in the Federal Civil Service which include, Environmental Scientist (Federal Environmental Protection Agency/Federal Ministry of Environment); National Focal Point for the United Nations Convention to Combat Desertification (UNCCD); Technical Coordinator for the Great Green Wall Programme at GGW Programme Implementation Unit (PIU); and Director (Planning and Policy Analysis) at the National Agency for the Great Green Wall (NAGGW). <br /> <br />Mr. Katsina participated in many international conferences and meetings and these include among others, Preparatory Technical Meeting for the Nigeria- Niger Transboundary Ecosystem Management Project (Niamey, Niger Republic); UNCCD COP 10 (Changwon, S/Korea); UNCCD CRIC 14 (Ankara, Turkey); UNCCD COP 13 (Ordos, China); CRIC 17 (Georgetown, Guyana); UNCCD Cop 14 (New Delhi, India); and Regular Technical and Ministerial Meetings on Great Green Wall (Chad, Senegal, Sudan and Mauritania).",
    img: "/images/sani-mamman.png",
  },
  {
    id: "jauro_jibrin",
    next: "saminu_ado",
    name: "Jauro Jibin",
    post: "Executive Director - Finance and Administration",
    summary:
      "A qualified Chartered Accountant with wide experience in financial and personnel management,Jauro Jibrin is the Executive Director, Finance and Administration of GSC.",
    desc: "Jibrin attended the famous Kaduna Polytechnic and obtained National Diploma and Higher National Diploma in Accounting. He also obtained a Post Graduate Diploma in Business Administration from the same Polytechnic and Masters Degree in Business Administration from University of Abuja. Other professional trainings he attended include; Training on Combating Corruption and Developing Organizational Integrity organized by Crown Agents, UK; Computer training course on Systems Analysis and Design at Ahmadu Bello University, Zaria.",
    further_desc:
      "Jibrin is a member of numerous professional bodies that include; Chartered Institute of Taxation in Nigeria (CITN); Institute of Certified Public Accountants of Nigeria (ICPAN); Chartered Member of Association of National Accountants of Nigeria (CAN); Nigerian Institute of Management; Member/Fellow of Chartered Institute of Taxation of Nigeria and Examiner of Chartered Institute of Taxation of Nigeria. Jibrin was in the Federal Civil Service where he held various positions including; Deputy Director of Finance and Accounts (National Board for Technical Education, Kaduna); Deputy Director of Finance and Accounts of Finance and Accounts (Federal Ministry of Transport, Abuja); Acting Director of Finance and Accounts (National Centre for Women Development, Abuja); Acting Director of Finance and Accounts (Federal Ministry of Women Affairs, Abuja); and Director of Finance and Administration (National Agency for the Great Green Wall, Abuja). In recognition of his contribution to societal development, Professional Bodies, Student Associations, States and Town Development Unions and Associations have honoured Alhaji Jibrin with numerous awards.",
    img: "/images/jauro-jibrin.png",
  },
  {
    id: "saminu_ado",
    next: "isa_waziri",
    name: "Dr Saminu Ado",
    post: "Executive Director - Afforestation & Extension Service",
    summary:
      "A prominent Forester with long track of practical experience spanning over 30 years, Dr. Saminu Ado Wangara, as the Executive Director, Afforestation and Extension Services is one of the strong pillars of GSC.",
    desc: "Dr. Ado attended the famous Federal School of Forestry, Ibadan and obtained OND and HND in Forestry. He also holds a Postgraduate Diploma in Agricultural Management from University of Ilorin; Post Graduate Diploma and PhD in Environmental Management from Bayero University, Kano. Other professional trainings and certificates obtained include, Project Implementation and Control at Rural Management Institute (ARMTI), Ilorin; Training of Trainers in Agriculture and Development, sponsored by USDA in Washington DC, USA; Training and Development organised by Crown Agent in UK; Strengthening Training and Education in Agroforestry, Kumasi Ghana; Crop Production and Sustainable Development in the Arid and Semi- Arid Regions, organised by the Embassy of Israel; Project Management at ARMTI, Ilorin; Administrative Processes and Procedures , ASCON Badagry; Gum Arabic Best Practices Workshop for Small Traders and Farmers on Tree Management, Harvesting and Marketing, organised by ARD/USAID; Climate Change and Desertification Process, Assessment and Monitoring, organised by WMO Regional Meteorological Training Centre, Bet- Degan, Israel; Shelterbelt Establishment Techniques, Institute of Ecology and Geography, Urumqi, China; and Forestry management organised by World Forestry Centre, Portland, Oregon USA.",
    further_desc:
      "Dr. Ado served in both Kano State and Federal Civil Service and held many positions including, Area Forest Officer (Kano State Ministry of Agriculture); Lecturer at the Department of Forestry, Audu Bako College of Agriculture, Danbatta, Kano state; Extension and Training Officer, Forestry Department, Ministry of Agriculture and Natural Resources, Kano; Zonal Shelterbelt Officer for the World Bank Forestry II Project, Kano; Principal, Forestry Vocational Training Centre of the World Bank Assisted Afforestation Programme Coordinating Unit, Kano; Capacity Building Officer, GGW Programme Implementation Unit (PIU), Federal Ministry of Environment, Abuja; and Director and Head of State Offices, National Agency for the Great Green Wall, Abuja. A one time President of Forestry Association of Nigeria, Dr. Ado is a Life Member and Fellow of Forestry Association of Nigeria; Distinguished Member of Commonwealth Forestry Association; Member, Agricultural Society of Nigeria; Member, Environmental Society of Nigeria; Member, Nigerian Society for Biological Conservation; Member, World Forestry Society of America; Member, Institute of Training and Development and Fellow of Horticultural Society of Nigeria. In addition to these accomplishments, Dr. Ado serves as Consultant to African Desertification Control Initiative (ADCI); Member, Conference Organization and Review of papers for Forestry Association of Nigeria; Member of National Board for Technical Education on Accreditation of Forestry Programmes; External Assessor for Promotion Interview of Staff to Higher Cadre for College of Agriculture and Forestry; and Member, National Board for Technical Education on Resource Verification for New Programmes in Agriculture and Forestry. Dr. Ado has numerous Publications in International and Local Scientific Journals and Books.",
    img: "/images/samino-ado.png",
  },
  {
    id: "yarima_peter",
    next: "isa_waziri",
    name: "Dr. Yarima Peter Tarfa",
    post: "Executive Director - Climate Change and Sustainable Development",
    summary:
      "Dr. Yarima Peter Tarfa, a widely recognized expert in Climate Change with three decades of working experience, holds a Bsc Degree in Biochemistry from University of Maiduguri, Msc in Biochemistry from Ahmadu Bello University and PhD in Environmental Resource Management from Nasarawa State University. Other professional certificates he obtained include, Certificate in Environmental Management; Certificate in International Climate Change Negotiation; Certificate in Operational Project Programming; and Certificate in Basic and Advanced Management Development.",
    desc: "Dr. Tarfa joined the Federal Civil Service and rose through the ranks to the position of Federal Permanent Secretary. Among the positions, Dr. Tarfa held include, Permanent Secretary, Federal Ministry of Labour and productivity; Director and Chief Technical Adviser on Climate Change; Chief Lead of Negotiating Team on Climate Change for Nigeria; National Focal Point to United Nations Framework Convention on Climate Change (UNFCCC), the Kyoto Protocol and Paris Agreement; Designated National Authority for Kyoto Protocol Clean Development Mechanism (CDM); National Designated Authority for the Green Climate Fund; Focal Point to the Intergovernmental Panel on Climate Change (IPCC); Coordinator, Nigerian Green Bond Programme; Coordinator, UNDP-NDC Support Programme for Implementation of Nationally Determined Contribution to Paris Agreement on Climate Change; Reform Champion and Coordinator, Implementation of the Executive Order EO-001 2017 on Ease of Doing Business by the MDAs; Member, Advisory Board of the United Nations Environment Programme (UNEP), Climate Change Technology Centre and Network; Member, Kyoto Protocol Adaptation Fund Board and Vice Chair , Programme and Project Review Committee; Member, Review of Project Concept Notes for funding by the Green Climate Fund (GCF); Monitoring of Reduction of Greenhouse Gas Emission and inclusion of Sustainable Development Criteria in CDM Projects; Sectoral Assessment of Vulnerability and Adaptation to the Impact of Climate Change and Monitoring of National Data Collection and Achieving for Inventory of Greenhouse Gas Emissions.",
    further_desc:
      "While in the Federal Civil Service, Dr. Tarfa attended numerous conferences, seminars and workshops and these among others include, Vulnerability and Adaptation Assessments Hand-ontraining workshop of the Consultative Group of Experts, Mozambique; Africa Climate Change Fellowship programme, Tanzania; Utilization of non-metallic sorbents for pollution control, Czechoslovakia; World Bank Environmental Management Programme on oil spill detection and remediation in pollution control, USA; training on Negotiation skill, Vulnerability Assessment and Implementation of UNFCCC, Germany and South Africa; Regional CDM DNA Forum for Africa and Second Africa Carbon Forum, UNEP HQ Nairobi, Kenya; Annual UNFCC Conference of Parties (COP 5 – 26); International Visitor Leadership Programme, USA; Annual National Council on Environment (NCE); Annual United Nations General Assembly (2016 – 2019). Dr. Tarfa is a member of International Partnership for Climate Change Mitigation; Africa Low Emission Development Strategy; and Fellow, US international Visitor Leadership. <br /> In recognition of the service he offered to the Nation and Global Community at large particularly on Climate Change issue, Dr.Tarfa received a number of awards, including; Special Recognition Award on his contribution to Nigeria’s Hosting of the International Conference on Lake Chad; Merit Award in recognition of his contribution to Climate Change Governance in Nigeria; Certificate of Achievement by the European Union (EU); and Academic Excellent Award as the best PhD Graduate in Environmental Resource Management, Nasarawa State University. In the course of his duties, Dr. Tarfa visited more than Fourty countries in Europe, Asia, Africa, North and South America.",
    img: "/images/yarima-tarfa.png",
  },
  {
    id: "isa_waziri",
    next: "engr_aminu",
    name: "Barr. Isa Waziri",
    post: "(Company Secretary /Legal Adviser)",
    summary:
      "Barr. Isa Waziri, the company Secretary/Legal Adviser graduated from University of Maiduguri with LLB (Bachelor of Law) Degree. As Secretary/Legal Adviser, Barr. Waziri is responsible for ensuring the compliance of GSC with statutory and regulatory requirements, as well as maintaining its high standards of corporate governance.",
    desc: "Before joining GSC, Barr. Waziri worked with Corporate Affairs Commission (CAC) and through the ranks rose to the position of Zonal Head at Damaturu, Yobe State.Among the numerous training workshops and professional training Barr. Waziri attended include; Training on Pre and Post Incorporation Documentation in CAC; Code of Conduct Bureau Compliance Training Programme for Public Officers; Record Keeping and Office Administration; Special Training for Legal Officers on Effective Legal Drafting Skills. Corporate Governance, Communication and Interprtion Skill. Barr. Waziri is a member of Nigeria Bar Association (NBA); Fellow Business Recovery and Insolvency Practitioners Association of Nigeria (BRIPAM); Associate Chartered Institute of Forensics and Certified Fraud Examiners of Nigeria (CFCFEN).",
    further_desc: "",
    img: "/images/isa.svg",
  },
  {
    id: "engr_aminu",
    name: "Engr. S.P Aminu",
    post: "(Executive Director - Engineering Services)",
    summary:
      "Engr. S.P Aminu, a Civil Engineer with wealth of practical experience, graduated from Ahmadu Bello University (ABU), Zaria with B.Engr. Degree (Civil) and Msc in Facility Management.",
    desc: "COREN registered and member of the Nigeria Society of Engineers and International Facility Management Association, Engr. Aminu designed and supervised the implementation of numerous engineering projects and programmes in Nigeria and these include among others; Housing constructions in Kebbi State, Jigawa State, Lagos State, Ondo State and Abuja; Flood and Erosion Control of Bunjang Town in Bauchi State; Feasibility Report, Environmental Impact Assessment and Design of Flood and Erosion Control of Iju-Ode Town; Design, preparation of Tender Document, Priced Bill of Engineering Measurement and Evaluation (BEME) of Akure Township Road Zone A, Zone B and Ondo State University Link Road; Supervision of the Construction of Flood and Erosion Works of Oke-Oka Town and; Design, Route Survey, Preparation of Tender  Document and Priced Bill of Engineering Measurement (BEME) of Igbokoda- Orere-Ara – Aboto – Mohin – Ayetoro Road in Mangrove Swampy Terrain.",
    further_desc: "",
    img: "",
  },
];
